### ISSUE TITLE
Критерий - использование == для сравнения строк

### ISSUE THREAD

**Issue by AndrewGavril** [moevm/oclint_extensions#13]
В некоторых случаях оператор == будет давать корректный результат (если  в переменную записывается указатель на константную строку, а потом сравнивается с этой константной строкой), но в общем смысле это неизбежно приведет к ошибке

**Comment by jcdkiki** [comment]
В OCLint уже есть такой критерий, но он отлавливает далеко не все такие случаи. Отлавливает только сравнения с константными строковыми литералами, т.е.
```c
"Hello" == "World"
"Hello" == str
str == "World"
// И аналогичные с '!='
```

Мое решение также отлавливает сравнение переменной с переменной:
```c
str1 == str2
// И даже
char **arr;
arr[1] == arr[2]
```

В общем, оно отлавливает сравнение любых выражений, имеющих тип "char*" или подобный.

Код лежит в `rules/StringCompareRule.cpp`
Пример лежит в `examples/ex-string-compare/main.c`

Коммит: [84c7ef1](https://github.com/moevm/oclint_extensions/pull/9/commits/84c7ef10468cd2dd985468174d11f47de785baa3)

**Comment by jcdkiki** [comment]
UPD:
В OCLint такого критерия нет. Это он выдавал варнинги clang'а `result of comparison against a string literal is unspecified (use an explicit string comparison function instead)`

Для проверки типа я использую метод `isAnyCharacterType()`. Но он почему-то не распознает wchar_t. Разберусь с этим позже.

Скорее всего, потому что wchar_t определен где-то как `typedef unsigned short wchar_t;`, но я не уверен.

**Comment by jcdkiki** [comment]
На моем ноуте, в моей системе, с моим компиляторам широкие строковые литералы имеют тип `int *` . Это не символьный тип, и это плохо.

В последнем коммите написал решение, как по мне, немного грязное, зато рабочее. Единственные случаи, которые оно не отлавливает -- это сравнение двух широких строковых литералов. В глазах oclint'а это получается сравнение двух значений типа `int *`, то есть не имеет к строкам никакого отношения. Но, я уверен, никто в своих лабораторных и курсовых так (`L"Hello" == L"World"`) не пишет, поэтому это не проблема.
