### ISSUE TITLE
Скрипты для сброки проекта

### ISSUE THREAD

**Issue by mirrin00** [moevm/oclint_extensions#6]
Bash скрипты, которые все склонируют и всё соберут, чтобы руками не пришлось делать лишних действий

**Comment by zmm** [comment]
+ скрипты которые поставят все необходимые зависимости (в предположении, что их запускают на ubuntu 22.02)

**Comment by jcdkiki** [comment]
CMake не видит Ninja

**Comment by mirrin00** [comment]
> CMake не видит Ninja

По такому сообщению не очень понятно в чем проблема и есть ли она

1. Является ли это блокирующим фактором в выполнении задачи (и почему)
2. Почему не использовать `make`, если не получается `ninja`?
3. Какие логи ошибки?
4. Пробовали ли вы искать ошибку в интернете?

**Comment by jcdkiki** [comment]
У меня на Debian 12 и WSL Ubuntu 22.04 всё собиралось без проблем. Я вообще этот комментария лично для себя оставил, чтобы не забыть внести ninja в список зависимостей. Не думал что кто-то читать будет. 

1. Не является
2. В списке зависимостей oclint (https://oclint-docs.readthedocs.io/en/stable/intro/build.html) есть Ninja -- система сборки. Она используется внутри oclint во время сборки его самого или его зависимостей. Значит избавиться от зависимости можно только если не собирать oclint вовсе. От сборки oclint отказаться нельзя, поскольку самописные критерии (как и критерии oclint) линкуются с *.a файлами, которые в свою очередь создаются в процессе сборки oclint.
3. Ошибка решается банально `sudo apt install ninja-build`.

Короче, это не ошибка сборки, а ошибка документации, которая дает читателю неполный список зависимостей.
